# Generated by Django 4.2.1 on 2023-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='cotegory',
            name='name',
            field=models.CharField(max_length=122),
        ),
    ]
